INSERT INTO ACCOUNTS (balance) VALUES ('1000');
INSERT INTO ACCOUNTS (balance) VALUES ('2000');
INSERT INTO ACCOUNTS (balance) VALUES ('3000');
INSERT INTO ACCOUNTS (balance) VALUES ('4000');
INSERT INTO ACCOUNTS (balance) VALUES ('5000');
INSERT INTO ACCOUNTS (balance) VALUES ('6000');
INSERT INTO ACCOUNTS (balance) VALUES ('7000');
INSERT INTO ACCOUNTS (balance) VALUES ('8000');
INSERT INTO ACCOUNTS (balance) VALUES ('9000');
INSERT INTO ACCOUNTS (balance) VALUES ('10000');

INSERT INTO OPERATIONS (OP_ID, USER_ID, OPERATION_DATE, OPERATION_TYPE,AMOUNT,DESCRIPTION)
    VALUES (10,1,'2022-01-01', 'DEBIT', 1000, 'FUEL');
INSERT INTO OPERATIONS (OP_ID, USER_ID, OPERATION_DATE, OPERATION_TYPE,AMOUNT,DESCRIPTION)
    VALUES (20,1,'2022-02-01', 'DEBIT', 300, 'FUEL');
INSERT INTO OPERATIONS (OP_ID, USER_ID, OPERATION_DATE, OPERATION_TYPE,AMOUNT,DESCRIPTION)
    VALUES (30,1,'2022-03-01', 'DEBIT', 1500, 'FUEL');
INSERT INTO OPERATIONS (OP_ID, USER_ID, OPERATION_DATE, OPERATION_TYPE,AMOUNT,DESCRIPTION)
    VALUES (40,1,'2022-04-01', 'CREDIT', 1000, 'SALARY');