DROP TABLE IF EXISTS ACCOUNTS CASCADE;
CREATE TABLE IF NOT EXISTS ACCOUNTS(
                        USER_ID SERIAL PRIMARY KEY NOT NULL,
                        BALANCE NUMERIC
);

DROP TABLE IF EXISTS OPERATIONS CASCADE;
CREATE TABLE IF NOT EXISTS OPERATIONS(
    OP_ID SERIAL PRIMARY KEY NOT NULL,
    USER_ID INTEGER,
    OPERATION_DATE DATE,
    OPERATION_TYPE VARCHAR(50),
    AMOUNT NUMERIC,
    DESCRIPTION VARCHAR(50) DEFAULT NULL,
    FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS(USER_ID)
)